### PR TITLE
Update humio.go

### PR DESCRIPTION
**Pull request by srindal**
Updated url from /dataspaces/{REPO}/queryJobs to /repositories/{REPO}/query

### CODE REVIEW

**Comment by Crevil** [comment]
Thank you for the contribution 🙏 

Can you point me to some documentation as to when this URL changed? I can see in the [Humio Search API docs](https://docs.humio.com/reference/api/search-api/) that the URL contains `repositories` instead of dataspaces, but I can't find anything about `dataspaces` being removed?

**Comment by Crevil** [comment]
Ah, I think I found something in release 1.1.0: https://docs.humio.com/notices/releases/all/#v1.1.0

**Comment by Crevil** [comment]
Can you give us some information as to why this is necessary? Did you have any issues with the current implementation that was fixed by this change?

**Comment by srindal** [comment]
Hi Bjørn

It didnt work until I updated the URL. I discussed the issue on Humio Slack and thats what led me to the fix. 

I Got 403 fra Humio with the Old URL.

Brgds
Søren

Sendt fra min iPhone

**Comment by Crevil** [comment]
Interesting. I just saw the message now and I'll quote it here for completeness.

> Hi Humio, We're introducing Prometheus in my organisation, and I'm trying to convert Humio queries into Prometheus metrics. I have looked at this: https://github.com/lunarway/humio_exporter/ but it seems somewhat limited with regards to the types of queries that you can run, but I'm also not able to even get it to work. I'm on cloud.humio.com, so I run: `docker run -p 9534:9534 c6096d1ba51b --humio.api-token XXXXXXXXXXXXXXXXXX --humio.url https://cloud.humio.com --config queries.yaml` but I keep getting 403 Forbidden back.
So the question is: Is anybody able to pinpoint what I'm doing wrong with the humio_exporter and/or do you have suggestions for alternative approaches?

We are not using the cloud solution so it seems there might be a difference between that and on-prem installations?

Can you share an example of the queries you are using?

**Comment by srindal** [comment]
Hi Bjørn

I just have one example running in the exporter for now:

queries:
- query:
logtype=applicationlog application=bill /controlfee inserted/i
class=INFO env=prd|count()
  repo: Driftportalen
  interval: 1h
  metric_name: controlfees



I guess I will refer to stored queries in Humio instead of typing the full
query in the HumioExporter.

With regards to the limited set of commands - I haven't faced any problems
yet, I just noticed that you don't support all queries and wonder why. Off
course they need to return a single metric.

In my local example I manually changed the refresh rate from 5000 to 30000.

Brgds
Søren

**Comment by Crevil** [comment]
I'm unable to replicate any issues with the current implementation and provided query.

Using the changes of this PR we cannot start live queries, which is what is used.

```
INFO[0000] Failed to start job humio_status_total: start query 'count(status)' job: request not OK: 400 Bad Request: body: Live queries that use aggregate functions cannot be served by this endpoint. Use another search endpoint.  source="main.go:154"
ERRO[0000] Humio_exporter exited due to error: start query 'count(status)' job: request not OK: 400 Bad Request: body: Live queries that use aggregate functions cannot be served by this endpoint. Use another search endpoint.  source="main.go:134"
```

I will need some additional details about the setup to help out with this as I cannot replicate and provided patch breaks the functionality. 🤔

**Review by Crevil — CHANGES_REQUESTED** [review]
Per above comment

**Comment by srindal** [comment]
Did you run your tests on cloud humio or a local instance? I'm on cloud and the original endpoint didn't work for me. Maybe the solution is to support both endpoints and make it parameter controlled?

**Comment by Crevil** [comment]
I ran it against an on-prem instance. Interesting if it is a difference in the cloud implementation?
I'll see if I can replicate against that.

**Comment by Crevil** [comment]
I see the same against cloud. This is the logs from a run of this fork.

```
go build . && ./humio_exporter --humio.api-token='redacted' --humio.url https://cloud.humio.com --config ./examples/queries.yaml
INFO[0000] Starting job controlfees                      source="main.go:151"
INFO[0000] Listening on :9534                            source="main.go:123"
INFO[0000] Failed to start job controlfees: request not OK: 400 Bad Request: body: Live queries that use aggregate functions cannot be served by this endpoint. Use another search endpoint.  source="main.go:154"
ERRO[0000] Humio_exporter exited due to error: request not OK: 400 Bad Request: body: Live queries that use aggregate functions cannot be served by this endpoint. Use another search endpoint.  source="main.go:134"
```

```yaml
queries:
- query: logtype=applicationlog application=bill /controlfee inserted/i class=INFO env=prd|count()
  repo: humio-audit
  interval: 1h
  metric_name: controlfees
```

**Comment by srindal** [comment]
Hi Bjørn, I'm totally confused now. I went in to produce a complete example with my metrics, queries, snippets from humio.go and everything - but my humio.go has the original url-scheme, and it's working just fine in my container in kubernetes. I have no idea what happened, but I'm sorry that I disturbed you with my problems :-(

**Comment by Crevil** [comment]
Great to have it resolved. No worries. We are here to help 👍 

Thank you for using the project and let us know if you encounter anything else out of the ordinary.

**Pull request closed without merging**
